### PR TITLE
Fix > 4GB memory be filtered out by filter_memory_map()

### PR DESCRIPTION
**Pull request by os369510**
If the size of initramfs grows bigger, then grub will probably not able
to load initramfs (LP: #1842320).

Although kernel_alloc() support > 4GB for kernel/initramfs, the
retrieved memory map from EFI_BOOT_SERVICES.GetMemoryMap() has been
limited with 2 GB. (0x7fffffff)
Remove the limitation to align the GRUB_EFI_MAX_USABLE_ADDRESS to make
the > 4 GB memory allocation works.

### CODE REVIEW

**Comment by os369510** [comment]
@vathpela hi, would you please help to review this?
I can confirm the fedora 36 has the same problem if initramfs grows up to 500MB ~ 800MB

**Comment by os369510** [comment]
@frozencemetery would you please help to review this?

**Comment by julian-klode** [comment]
So https://github.com/rhboot/grub2/commit/635f85b016839b9aaecdecee69a2ee98edb3e0ab was supposed to allow initrds to be allocated over 4GB. However, initrds are also being verified by the verifiers framework, or rather the tpm "verifier" measures them this way.

This causes the verifiers framework to read the entire file into memory first using standard memory allocation to verify it and then release it again before our allocator gets a chance to load the size and allocate it. This is um bad.

*Presumably* this is the wrong fix (I'm not sure if it allows the kernel to end up being allocated > 4GB or if there are other issues), and the right fix involves patching our custom allocator into the memory management code so that when the verifiers framework opens an initrd it can allocate it above 4 GiB

**Comment by frozencemetery** [comment]
We've taken #114 for the moment.  Can revisit this if there are problems with that.

**Pull request closed without merging**
